# Project information
site_name: "Codacy docs"
site_description: "Documentation for the Codacy automated code review tool"
site_url: "https://docs.codacy.com/"
site_author: "support@codacy.com"

# Copyright
copyright: "© <script>document.write(new Date().getFullYear())</script> <a href=\"https://www.codacy.com\">Codacy</a> - Automated code review"

# Configuration
theme:
    name: "material"
    custom_dir: "submodules/codacy-mkdocs-material/material"
    font: false
    language: en
    favicon: "assets/images/favicon.ico"
    palette:
        primary: indigo
        accent: indigo
    logo: "assets/images/codacy-docs-logo.svg"
    features: []

extra_css:
    - "assets/stylesheets/version-select.css"
extra_javascript:
    - "assets/javascripts/extra.js"
    - "assets/javascripts/version-select.js"

strict: true

# Extra variables
extra:
    version: 3.0.0
    segment_key: "4sT1ml0BeKdR1RtrK5dSQmwxmvcUpYtL"
    user_feedback: "true"
    community_url: "https://community.codacy.com/"
    support_email: "support@codacy.com"

# Repository
repo_name: "codacy/docs"
repo_url: "https://github.com/codacy/docs"
edit_uri: "" # Hide the edit button

# Extensions
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
          guess_lang: false
          linenums: true
    - footnotes
    - meta
    - pymdownx.superfences
    - pymdownx.striphtml:
          strip_comments: true
    - toc:
          permalink: true
          toc_depth: 2

# Plugins
plugins:
    - search
    - git-revision-date-localized
    - monorepo
    - markdownextradata
    - redirects:
          redirect_maps:
              # Deleted pages
              "faq/repositories/what-are-logs.md": "index.md"
              "faq/repositories/hotspots-overview.md": "index.md"
              "chart/configuration/tls-ingress.md": "index.md"
              "getting-started/setting-up-your-personal-repositories.md": "getting-started/getting-started-with-codacy.md"
              "getting-started/supported-languages.md": "getting-started/supported-languages-and-tools.md"
              # Moved pages
              "faq/general/plan-and-billing.md": "faq/general/how-can-i-change-or-cancel-my-plan.md"
              "organizations/why-can't-i-see-my-organization.md": "faq/general/why-cant-i-see-my-organization.md"
              "repositories-configure/integrations/bitbucket-cloud-integration.md": "repositories-configure/integrations/bitbucket-integration.md"
              "repositories-configure/add-coverage-to-your-repo.md": "coverage-reporter/adding-coverage-to-your-repository.md"
              "repositories-configure/coverage.md": "coverage-reporter/adding-coverage-to-your-repository.md"
              "repositories-configure/generate-coverage.md": "coverage-reporter/generating-coverage-reports.md"
              "coverage-reporter.md": "coverage-reporter/adding-coverage-to-your-repository.md"
              "coverage-reporter/advanced/authenticating-using-account-token.md": "coverage-reporter/adding-coverage-to-your-repository.md"
              "coverage-reporter/advanced/multiple-reports.md": "coverage-reporter/adding-coverage-to-your-repository.md"
              "coverage-reporter/advanced/installation-methods.md": "coverage-reporter/alternative-ways-of-running-coverage-reporter.md"
              "coverage-reporter/troubleshooting/common-issues.md": "coverage-reporter/troubleshooting-common-issues.md"
              "coverage-reporter/troubleshooting/commit-detection.md": "coverage-reporter/adding-coverage-to-your-repository.md"
              "coverage-reporter/troubleshooting/swift-objectivec.md": "coverage-reporter/generating-coverage-reports.md"
              "faq/troubleshooting/failed-to-clone-the-repository-generate-a-new-ssh-key.md": "faq/troubleshooting/we-no-longer-have-access-to-this-repository.md"
              "organizations/organization-dashboard-overview.md": "organizations/organization-overview.md"
              "repositories/repository-dashboard-overview.md": "repositories/repository-dashboard.md"
              "repositories/share-your-repository-with-a-non-codacy-user.md": "organizations/manual-organizations/share-your-repository-with-a-non-codacy-user.md"
              "faq/repositories/how-do-i-transfer-delete-a-repository-from-my-account.md": "faq/repositories/how-do-i-migrate-a-legacy-repository-to-a-synced-organization.md"
              "repositories/security-dashboard.md": "repositories/security-monitor.md"
              "related-tools/engines.md": "getting-started/supported-languages-and-tools.md"
              "faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-my-prs.md": "faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-prs.md"
              "faq/troubleshooting/why-isnt-codacy-commenting-on-pull-requests-anymore.md": "faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests.md"

nav:
    - "Documentation home": "index.md"
    - "Getting started":
          - getting-started/getting-started-with-codacy.md
          - getting-started/i-added-a-repository-now-what.md
          - getting-started/supported-languages-and-tools.md
          - getting-started/which-permissions-does-codacy-need-from-my-account.md
    - "Your repositories":
          - repositories/repository-dashboard.md
          - repositories/what-are-the-different-grades-and-how-are-they-calculated.md
          - repositories/issues-view.md
          - repositories/commits-view.md
          - repositories/files-view.md
          - repositories/security-monitor.md
          - repositories/badges.md
          - repositories/quality-settings.md
          - repositories/managing-branches.md
          - repositories/post-commit-hooks.md
          - repositories/removing-your-repository.md
    - "Configuring your repositories":
          - Integrations:
                - repositories-configure/integrations/github-integration.md
                - repositories-configure/integrations/gitlab-integration.md
                - repositories-configure/integrations/bitbucket-integration.md
                - repositories-configure/integrations/slack-integration.md
                - repositories-configure/integrations/jira-integration.md
                - repositories-configure/integrations/project-api.md
                - repositories-configure/integrations/webhook-notifications.md
          - repositories-configure/code-patterns.md
          - "Coverage": "!include submodules/codacy-coverage-reporter/mkdocs.yml"
          - repositories-configure/codacy-configuration-file.md
          - repositories-configure/ignore-files-from-codacy-analysis.md
          - repositories-configure/using-submodules.md
          - repositories-configure/file-extensions.md
          - repositories-configure/specifying-language.md
          - repositories-configure/specifying-your-python-version.md
          - repositories-configure/php_codesniffer-specifying-your-php-version.md
          - repositories-configure/code-standards.md
    - "Organizations":
          - organizations/what-are-synced-organizations.md
          - organizations/organization-overview.md
          - organizations/roles-and-permissions-for-synced-organizations.md
          - organizations/adding-and-managing-authors.md
          - organizations/authors-vs-members.md
          - organizations/how-to-configure-which-users-can-ignore-issues.md
          - organizations/managing-repositories-in-your-organization.md
          - "Manual organizations (legacy)":
                - organizations/manual-organizations/creating-and-renaming-an-organization.md
                - organizations/manual-organizations/creating-and-managing-teams.md
                - organizations/manual-organizations/managing-team-repositories.md
                - organizations/manual-organizations/administrative-permissions.md
                - organizations/manual-organizations/share-your-repository-with-a-non-codacy-user.md
    - "Your account":
          - account/managing-your-profile.md
          - account/notifications.md
    - "Related tools":
          - related-tools/codacy-plugin-tools.md
          - related-tools/client-side-tools.md
          - related-tools/run-local-analysis.md
          - related-tools/run-spotbugs.md
          - related-tools/api-tokens.md
          - related-tools/tool-developer-guide.md
          - related-tools/tool-developer-guide-using-scala.md
    - "Installing Codacy": "!include submodules/chart/mkdocs.yml"
    - Troubleshooting and FAQs:
          - General:
                - faq/general/which-version-control-systems-do-you-support.md
                - faq/general/which-browsers-do-you-support.md
                - faq/general/how-does-codacy-support-gitlab-cloud.md
                - faq/general/how-does-codacy-support-gitlab-enterprise.md
                - faq/general/how-does-codacy-support-bitbucket-cloud.md
                - faq/general/how-does-codacy-support-bitbucket-server.md
                - faq/general/how-does-codacy-keep-my-data-secure.md
                - faq/general/how-does-codacy-protect-my-privacy.md
                - faq/general/why-cant-i-see-my-organization.md
                - faq/general/how-do-i-change-my-email-address-in-codacy.md
                - faq/general/how-can-i-change-or-cancel-my-plan.md
          - Repositories:
                - faq/repositories/why-cant-i-see-or-add-my-organizations-repositories.md
                - faq/repositories/how-do-i-set-codacy-as-a-required-check-to-merge-prs.md
                - faq/repositories/how-do-i-manually-force-a-repository-update.md
                - faq/repositories/how-do-i-reanalyze-my-repository.md
                - faq/repositories/how-do-i-programmatically-add-repositories-to-codacy.md
                - faq/repositories/i-renamed-my-repository-on-the-git-provider.md
                - faq/repositories/i-moved-my-repository-on-the-git-provider.md
                - faq/repositories/how-do-i-migrate-a-legacy-repository-to-a-synced-organization.md
          - Code analysis:
                - faq/code-analysis/do-you-check-for-dependencies.md
                - faq/code-analysis/does-codacy-automatically-analyze-all-pull-requests.md
                - faq/code-analysis/how-does-codacy-measure-complexity-in-my-repository.md
                - faq/code-analysis/how-long-does-it-take-for-my-repository-to-be-analyzed.md
                - faq/code-analysis/error-line-endings.md
                - faq/code-analysis/skipping-an-analysis.md
          - Troubleshooting:
                - faq/troubleshooting/why-is-my-file-missing.md
                - faq/troubleshooting/why-did-codacy-stop-commenting-on-pull-requests.md
                - faq/troubleshooting/why-arent-duplication-metrics-being-calculated.md
                - faq/troubleshooting/not-a-member-of-the-organization.md
                - faq/troubleshooting/why-isnt-my-public-repository-being-analysed.md
                - faq/troubleshooting/we-no-longer-have-access-to-this-repository.md
                - faq/troubleshooting/why-cant-i-configure-post-commit-hooks-and-integrations.md
    - special-thanks.md
