name: Codacy Analysis CLI

on: push

jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    name: Codacy Analysis CLI
    if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/release/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCOUNT_TOKEN }}
      - name: Run codacy-analysis-cli
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
